// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
 import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEFsiYLmej2bBOKMiisf4GjGkNP_iMxQ',
    appId: '1:681491448286:web:dab5cd3b69fc9107e41d4f',
    messagingSenderId: '681491448286',
    projectId: 'crud-bloc-7cbd0',
    authDomain: 'crud-bloc-7cbd0.firebaseapp.com',
    storageBucket: 'crud-bloc-7cbd0.firebasestorage.app',
    measurementId: 'G-KFSF1600SV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALFoZ2WcSygtY6PWnzSXvI9ggvuSkDy28',
    appId: '1:681491448286:ios:b532ca55e978d4e8e41d4f',
    messagingSenderId: '681491448286',
    projectId: 'crud-bloc-7cbd0',
    storageBucket: 'crud-bloc-7cbd0.firebasestorage.app',
    iosBundleId: 'com.example.crudBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALFoZ2WcSygtY6PWnzSXvI9ggvuSkDy28',
    appId: '1:681491448286:ios:b532ca55e978d4e8e41d4f',
    messagingSenderId: '681491448286',
    projectId: 'crud-bloc-7cbd0',
    storageBucket: 'crud-bloc-7cbd0.firebasestorage.app',
    iosBundleId: 'com.example.crudBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMEFsiYLmej2bBOKMiisf4GjGkNP_iMxQ',
    appId: '1:681491448286:web:ac50f960ad316d37e41d4f',
    messagingSenderId: '681491448286',
    projectId: 'crud-bloc-7cbd0',
    authDomain: 'crud-bloc-7cbd0.firebaseapp.com',
    storageBucket: 'crud-bloc-7cbd0.firebasestorage.app',
    measurementId: 'G-3CT6TDM6HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscv8J2vDhzWrFcMXv_myHVCJDxzm_vL0',
    appId: '1:681491448286:android:f5537eeb1577a75ae41d4f',
    messagingSenderId: '681491448286',
    projectId: 'crud-bloc-7cbd0',
    storageBucket: 'crud-bloc-7cbd0.firebasestorage.app',
  );

}